# Generated by Django 6.1 on 2026-09-05 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCounter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfomodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
