# Generated by Django 6.1 on 2026-09-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofilemodel',
            name='skill_set',
            field=models.TextField(null=True),
        ),
    ]
